// <auto-generated />
using System;
using CMDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMDB.Migrations.EmployeesDb
{
    [DbContext(typeof(EmployeesDbContext))]
    partial class EmployeesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccessoriesEmployees", b =>
                {
                    b.Property<int>("AccessoriesAccessoryID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeesEmployeeID")
                        .HasColumnType("int");

                    b.HasKey("AccessoriesAccessoryID", "EmployeesEmployeeID");

                    b.HasIndex("EmployeesEmployeeID");

                    b.ToTable("AccessoriesEmployees");
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Accessories", b =>
                {
                    b.Property<int>("AccessoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccessoryID"));

                    b.Property<int?>("ComputersComputerID")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhonesPhoneID")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WarrantyExpiration")
                        .HasColumnType("datetime2");

                    b.HasKey("AccessoryID");

                    b.HasIndex("ComputersComputerID");

                    b.HasIndex("PhonesPhoneID");

                    b.ToTable("Accessories");
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Computers", b =>
                {
                    b.Property<int>("ComputerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComputerID"));

                    b.Property<int>("CPU")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeesEmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RAM")
                        .HasColumnType("int");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.HasKey("ComputerID");

                    b.HasIndex("EmployeesEmployeeID");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Employees", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Phones", b =>
                {
                    b.Property<int>("PhoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneID"));

                    b.Property<int?>("EmployeesEmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScreenSize")
                        .HasColumnType("int");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.HasKey("PhoneID");

                    b.HasIndex("EmployeesEmployeeID");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("AccessoriesEmployees", b =>
                {
                    b.HasOne("CMDB.Models.DBEntities.Accessories", null)
                        .WithMany()
                        .HasForeignKey("AccessoriesAccessoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMDB.Models.DBEntities.Employees", null)
                        .WithMany()
                        .HasForeignKey("EmployeesEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Accessories", b =>
                {
                    b.HasOne("CMDB.Models.DBEntities.Computers", null)
                        .WithMany("Accessories")
                        .HasForeignKey("ComputersComputerID");

                    b.HasOne("CMDB.Models.DBEntities.Phones", null)
                        .WithMany("Accessories")
                        .HasForeignKey("PhonesPhoneID");
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Computers", b =>
                {
                    b.HasOne("CMDB.Models.DBEntities.Employees", null)
                        .WithMany("Computers")
                        .HasForeignKey("EmployeesEmployeeID");
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Phones", b =>
                {
                    b.HasOne("CMDB.Models.DBEntities.Employees", null)
                        .WithMany("Phones")
                        .HasForeignKey("EmployeesEmployeeID");
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Computers", b =>
                {
                    b.Navigation("Accessories");
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Employees", b =>
                {
                    b.Navigation("Computers");

                    b.Navigation("Phones");
                });

            modelBuilder.Entity("CMDB.Models.DBEntities.Phones", b =>
                {
                    b.Navigation("Accessories");
                });
#pragma warning restore 612, 618
        }
    }
}
